### PR TITLE
added package.json for npm

### PR DESCRIPTION
**Pull request by arty-name**
It would be great to have that module in npm as well. It does not require any special formatting afaik, `package.json` is enough to be able to publish it by running `npm publish`.

### CODE REVIEW

**Comment by bachvtuan** [comment]
It have already supported  bower. Now support npm is fine too.

**Comment by arty-name** [comment]
Thank you! Would also be so kind to actually publish it?

**Comment by bachvtuan** [comment]
Ok. Please wait for 30. I am on mobile now.

**Comment by bachvtuan** [comment]
Here you are https://www.npmjs.com/package/html5-sortable-angularjs

**Comment by arty-name** [comment]
Sweet! Thank you!

**Comment by bachvtuan** [comment]
You're welcome :)

**Pull request merged**
